<form method="post" action="/?weblog/posts/save">
    <fieldset>
        <legend>Dodaj post</legend>
        <dl>
            <dt>Tytuł</dt>
            <dd>
                <?php echo $this->textInput('post', 'title'); ?>
                <?php echo $this->formFieldErrors('post', 'title'); ?>
            </dd>
        </dl>
        <dl>
            <dt>Autor</dt>
            <dd>

                <?php echo $this->textInput('post', 'author'); ?>
                <?php echo $this->formFieldErrors('post', 'author'); ?>
            </dd>
        </dl>
        <dl>
            <dt>Treść</dt>
            <dd>
                <?php echo $this->textarea('post', 'body'); ?>
                <?php echo $this->formFieldErrors('post', 'body'); ?>
            </dd>
        </dl>

        <?php echo $this->hidden('post', 'id'); ?>
        <input type="submit" value="Zapisz" />
    </fieldset>
</form>