<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8" />
        <title>Multipla</title>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->themePath() . '/multipla/css/style.css'; ?>"/>
    </head>
    <body>
        <div id="container">
            <?php echo $this->action('header', 'index', 'multipla'); ?>
            <?php echo $this->content(); ?>
        </div>
    </body>
</html>
