<h3>Posts</h3>

<?php if( ! empty($this->posts) ): ?>
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>tytuł</th>
            <th>autor</th>
            <th>operacje</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->posts as $p): ?>
        <tr>
            <td><?php echo $p->id; ?></td>
            <td><?php echo $p->title; ?></td>
            <td><?php echo $p->author; ?></td>
            <td>
                <ul>
                    <li>
                        <a href="<?php echo $this->url('weblog', 'posts', 'edit', array('id' => $p->id)); ?>"
                           title="Edytuj">
                           Edytuj
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('weblog', 'posts', 'remove', array('id' => $p->id)); ?>"
                           title="Usuń">
                           Usuń
                        </a>
                    </li>
                </ul>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
Nie dodano jeszcze żadnych postów
<?php endif; ?>